import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

function getArg(flag, fallback = undefined) {
  const index = process.argv.indexOf(flag);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

const sourcePath = path.resolve(projectRoot, getArg('--source', './skill/frontend-distill'));
const targetPathArg = getArg('--target');

if (!targetPathArg) {
  console.error('Missing required --target argument.');
  console.error('Example: npm run skill:install -- --target "C:\\Users\\name\\.claude\\skills"');
  process.exit(1);
}

const targetPath = path.resolve(projectRoot, targetPathArg);
const finalTarget = path.basename(targetPath).toLowerCase() === 'frontend-distill'
  ? targetPath
  : path.join(targetPath, 'frontend-distill');

function runtimeDocument() {
  return [
    '# Frontend Distill Runtime',
    '',
    'This file is generated by `tools/install-skill.mjs`.',
    'The installed skill should use the tool paths below instead of assuming the tools live inside the skill folder.',
    '',
    `Project root: ${projectRoot}`,
    `Automated site distill entry: ${path.join(projectRoot, 'tools', 'browser', 'distill-site.mjs')}`,
    `Browser fallback extractor: ${path.join(projectRoot, 'tools', 'browser', 'extract_design_tokens.js')}`,
    `Normalize bundle tool: ${path.join(projectRoot, 'tools', 'normalize-extraction-bundle.mjs')}`,
    `Validate bundle tool: ${path.join(projectRoot, 'tools', 'validate-extraction-bundle.mjs')}`,
    `Split bundle tool: ${path.join(projectRoot, 'tools', 'split-extraction-bundle.mjs')}`,
    '',
    'Typical automated command:',
    `node "${path.join(projectRoot, 'tools', 'browser', 'distill-site.mjs')}" --url "https://example.com" --output-dir "${path.join(projectRoot, 'output', 'example')}"`,
    '',
  ].join('\n');
}

try {
  await fs.mkdir(path.dirname(finalTarget), { recursive: true });
  await fs.rm(finalTarget, { recursive: true, force: true });
  await fs.cp(sourcePath, finalTarget, { recursive: true });
  await fs.writeFile(path.join(finalTarget, 'RUNTIME.md'), `${runtimeDocument()}\n`, 'utf8');

  console.log(`Installed skill from ${sourcePath}`);
  console.log(`Installed skill to   ${finalTarget}`);
  console.log(`Runtime guide written to ${path.join(finalTarget, 'RUNTIME.md')}`);
} catch (error) {
  console.error(`Failed to install skill: ${error.message}`);
  process.exitCode = 1;
}
